- id: doi:10.1109/ACCESS.2022.3141200
  type: journal
  # description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  # date: 2020-12-4
  image: https://ieeexplore.ieee.org/ielx7/6287639/9668973/9673749/graphical_abstract/access-gagraphic-3141200.jpg
  # buttons:
  #   - type: manubot
  #     link: https://greenelab.github.io/meta-review/
  #   - type: source
  #     text: Manuscript Source
  #     link: https://github.com/greenelab/meta-review
  #   - type: website
  #     link: http://manubot.org/
  tags:
    - NLP
    - transfer learning
    - zero-shot
    - text-to-speech
    - low-resource language
  # repo: greenelab/meta-review

- id: doi:10.1186/s40537-020-00374-x
  type: journal
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs40537-020-00374-x/MediaObjects/40537_2020_374_Fig2_HTML.png?as=webp
  tags:
    - robots
    - drones

- id: doi:10.1109/ACCESS.2020.2969021
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/6287639/8948470/8967069/husod1-2969021-large.gif
  tags:
    - robots
    - drones

- id: doi:10.1016/j.media.2020.101712
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1361841520300761-gr1_lrg.jpg
  tags:
    - biomedical
    - medical image analysis
